import type { SkillDef, SkillDomain } from '../types/skill'

/** 领域展示元数据 */
export const DOMAIN_META: Record<
  SkillDomain,
  { label: string; emoji: string; order: number }
> = {
  gross: { label: '大运动', emoji: '🏃', order: 1 },
  fine: { label: '精细动作', emoji: '✋', order: 2 },
  language: { label: '语言', emoji: '💬', order: 3 },
  cognition: { label: '认知专注', emoji: '🧩', order: 4 },
  selfcare: { label: '生活自理', emoji: '👟', order: 5 },
  social: { label: '社交', emoji: '👫', order: 6 },
  other: { label: '其他', emoji: '✨', order: 7 },
}

/**
 * 技能目录（来自 Mia 档案 27 个月评估 + 常见 2–3 岁节点）
 * 只记可观察行为，不写判断标签
 */
export const SKILL_CATALOG: SkillDef[] = [
  // —— 大运动 ——
  {
    id: 'gross-jump-two-feet',
    domain: 'gross',
    label: '双脚同时离地跳',
    emoji: '🦘',
    typicalFrom: 26,
    typicalTo: 32,
    sortOrder: 10,
  },
  {
    id: 'gross-stairs-rail',
    domain: 'gross',
    label: '扶栏杆一阶一阶上楼梯',
    emoji: '🪜',
    typicalFrom: 24,
    typicalTo: 36,
    sortOrder: 20,
  },
  {
    id: 'gross-kick-ball',
    domain: 'gross',
    label: '会踢球',
    emoji: '⚽',
    typicalFrom: 24,
    typicalTo: 30,
    sortOrder: 30,
  },
  {
    id: 'gross-tiptoe',
    domain: 'gross',
    label: '踮脚走',
    emoji: '🩰',
    typicalFrom: 28,
    typicalTo: 36,
    sortOrder: 40,
  },
  {
    id: 'gross-run-steady',
    domain: 'gross',
    label: '稳稳地跑',
    emoji: '🏃',
    typicalFrom: 24,
    typicalTo: 30,
    sortOrder: 50,
  },

  // —— 精细 ——
  {
    id: 'fine-blocks-7',
    domain: 'fine',
    label: '搭积木约 7–8 块',
    emoji: '🧱',
    typicalFrom: 24,
    typicalTo: 30,
    sortOrder: 10,
  },
  {
    id: 'fine-lego-duplo',
    domain: 'fine',
    label: '玩大颗粒乐高',
    emoji: '🧱',
    typicalFrom: 24,
    typicalTo: 36,
    sortOrder: 20,
  },
  {
    id: 'fine-draw-line-circle',
    domain: 'fine',
    label: '画线和圈',
    emoji: '✏️',
    typicalFrom: 24,
    typicalTo: 36,
    sortOrder: 30,
  },
  {
    id: 'fine-turn-pages',
    domain: 'fine',
    label: '一页页翻书',
    emoji: '📖',
    typicalFrom: 24,
    typicalTo: 30,
    sortOrder: 40,
  },
  {
    id: 'fine-twist-cap',
    domain: 'fine',
    label: '拧瓶盖',
    emoji: '🍼',
    typicalFrom: 24,
    typicalTo: 36,
    sortOrder: 50,
  },

  // —— 语言 ——
  {
    id: 'lang-talk-lots',
    domain: 'language',
    label: '表达欲强、话多',
    emoji: '🗣️',
    typicalFrom: 24,
    typicalTo: 36,
    sortOrder: 10,
  },
  {
    id: 'lang-two-word',
    domain: 'language',
    label: '会说两个词的短语',
    emoji: '🔤',
    typicalFrom: 18,
    typicalTo: 30,
    sortOrder: 20,
  },
  {
    id: 'lang-sing-along',
    domain: 'language',
    label: '会跟着唱歌',
    emoji: '🎵',
    typicalFrom: 24,
    typicalTo: 36,
    sortOrder: 30,
  },
  {
    id: 'lang-en-words',
    domain: 'language',
    label: '会说常见英语单词',
    emoji: '🔤',
    typicalFrom: 24,
    typicalTo: 48,
    sortOrder: 40,
  },
  {
    id: 'lang-what-sound',
    domain: 'language',
    label: '会问「这是什么声音」',
    emoji: '👂',
    typicalFrom: 24,
    typicalTo: 36,
    sortOrder: 50,
  },
  {
    id: 'lang-emotion-word',
    domain: 'language',
    label: '能说出简单情绪词',
    emoji: '😤',
    typicalFrom: 30,
    typicalTo: 42,
    sortOrder: 60,
  },

  // —— 认知 ——
  {
    id: 'cog-puzzle-9',
    domain: 'cognition',
    label: '能拼约 9 块拼图',
    emoji: '🧩',
    typicalFrom: 30,
    typicalTo: 42,
    sortOrder: 10,
  },
  {
    id: 'cog-love-books',
    domain: 'cognition',
    label: '喜欢看书听故事',
    emoji: '📚',
    typicalFrom: 18,
    typicalTo: 36,
    sortOrder: 20,
  },
  {
    id: 'cog-point-share',
    domain: 'cognition',
    label: '用手指指物分享',
    emoji: '👆',
    typicalFrom: 12,
    typicalTo: 24,
    sortOrder: 30,
  },
  {
    id: 'cog-pretend-play',
    domain: 'cognition',
    label: '简单假装游戏',
    emoji: '🧸',
    typicalFrom: 24,
    typicalTo: 36,
    sortOrder: 40,
  },

  // —— 自理 ——
  {
    id: 'care-shoes',
    domain: 'selfcare',
    label: '会自己穿鞋',
    emoji: '👟',
    typicalFrom: 24,
    typicalTo: 36,
    sortOrder: 10,
  },
  {
    id: 'care-pee-day',
    domain: 'selfcare',
    label: '白天小便基本自控',
    emoji: '🚽',
    typicalFrom: 24,
    typicalTo: 36,
    sortOrder: 20,
  },
  {
    id: 'care-poop-potty',
    domain: 'selfcare',
    label: '能在便盆大便',
    emoji: '🚽',
    typicalFrom: 30,
    typicalTo: 42,
    sortOrder: 30,
  },
  {
    id: 'care-brush-teeth',
    domain: 'selfcare',
    label: '配合刷牙',
    emoji: '🪥',
    typicalFrom: 24,
    typicalTo: 36,
    sortOrder: 40,
  },
  {
    id: 'care-wash-hands',
    domain: 'selfcare',
    label: '会洗手（需提醒）',
    emoji: '🧼',
    typicalFrom: 24,
    typicalTo: 36,
    sortOrder: 50,
  },

  // —— 社交 ——
  {
    id: 'soc-simple-play',
    domain: 'social',
    label: '和小朋友有简单互动',
    emoji: '👫',
    typicalFrom: 24,
    typicalTo: 36,
    sortOrder: 10,
  },
  {
    id: 'soc-game-rules',
    domain: 'social',
    label: '能听懂简单游戏指令',
    emoji: '🎲',
    typicalFrom: 30,
    typicalTo: 42,
    sortOrder: 20,
  },
  {
    id: 'soc-not-shy',
    domain: 'social',
    label: '见生人不太怕',
    emoji: '👋',
    typicalFrom: 24,
    typicalTo: 36,
    sortOrder: 30,
  },
  {
    id: 'soc-share-try',
    domain: 'social',
    label: '在提示下愿意分享',
    emoji: '🤝',
    typicalFrom: 30,
    typicalTo: 42,
    sortOrder: 40,
  },
]
