/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlanketSprite: typeof import('./components/BlanketSprite/BlanketSprite.vue')['default']
    ChipGroup: typeof import('./components/ChipGroup.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    EventItem: typeof import('./components/EventItem.vue')['default']
    EventMediaAttach: typeof import('./components/EventMediaAttach.vue')['default']
    MiaConfirmDialog: typeof import('./components/MiaConfirmDialog.vue')['default']
    MiaDateTimePicker: typeof import('./components/MiaDateTimePicker.vue')['default']
    MiaFormDialog: typeof import('./components/MiaFormDialog.vue')['default']
    MiaMarkdown: typeof import('./components/MiaMarkdown.vue')['default']
    QuoteBubble: typeof import('./components/BlanketSprite/QuoteBubble.vue')['default']
    RankCard: typeof import('./components/analytics/RankCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SceneCards: typeof import('./components/SceneCards.vue')['default']
    SpriteImage: typeof import('./components/BlanketSprite/SpriteImage.vue')['default']
    StatBar: typeof import('./components/analytics/StatBar.vue')['default']
    TypeChip: typeof import('./components/TypeChip.vue')['default']
  }
}
